# Generated by Django 3.2.3 on 2022-03-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('texto', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
