# Generated by Django 4.0.1 on 2022-03-01 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sapiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('escrito_por', models.CharField(max_length=80)),
                ('data_postagem', models.DateField(blank=True, default=datetime.datetime.now)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/sapiencia')),
            ],
            options={
                'ordering': ('data_postagem',),
            },
        ),
    ]
