# Generated by Django 3.2.3 on 2022-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacto', '0002_auto_20220309_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempacto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
