# Generated by Django 4.0.1 on 2022-03-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemide',
            options={'ordering': ('ide', 'titulo')},
        ),
        migrations.RemoveField(
            model_name='imagemide',
            name='ide',
        ),
        migrations.AddField(
            model_name='imagemide',
            name='ide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ide.ide'),
        ),
    ]
