# Generated by Django 4.0.1 on 2022-03-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_alter_imagemide_options_remove_imagemide_pacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ide',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
