# Generated by Django 3.2.3 on 2022-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_auto_20220309_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='ide',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagemide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
