# Generated by Django 4.0.1 on 2023-03-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_ide_texto'),
        ('ide', '0004_auto_20220309_1846'),
    ]

    operations = [
    ]
