# Generated by Django 4.0.1 on 2022-03-01 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Plapla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('escrito_por', models.CharField(max_length=80)),
                ('data_postagem', models.DateField(blank=True, default=datetime.datetime.now)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria/plapla')),
                ('link', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapla.categoria')),
            ],
            options={
                'ordering': ('data_postagem', 'categoria'),
            },
        ),
    ]
