# Generated by Django 4.0.1 on 2022-03-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPresente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=80)),
                ('presenteado_por', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='galeria/lista_presente')),
            ],
            options={
                'ordering': ('produto',),
            },
        ),
    ]
