# Generated by Django 4.0.1 on 2022-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_presentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapresente',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listapresente',
            name='presente',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='listapresente',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listapresente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/lista_presentes'),
        ),
        migrations.AlterField(
            model_name='listapresente',
            name='presenteado_por',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='listapresente',
            name='produto',
            field=models.CharField(max_length=200),
        ),
    ]
